### ISSUE TITLE
Update home path to accomodate pi or rms user

### ISSUE THREAD

**Issue by g4t3y** [markmac99/ukmon-pitools#72]
[liveMonitor.py](https://github.com/markmac99/ukmon-pitools/blob/bb51060c1c55abb2f785700f0c596a2b032dce57/liveMonitor.py#L165)
refers to rmscfg = '/home/pi/source/RMS/.config' but with the Bullseye build of RMS with a default RMS user this will be .../home/rms/...

[restartLiveMon.sh](https://github.com/markmac99/ukmon-pitools/blob/bb51060c1c55abb2f785700f0c596a2b032dce57/restartLiveMon.sh#L7)
also mentions this path for the pi user but only as comment

**Comment by markmac99** [comment]
This isn't actually a bug. 
The python script is only ever invoked from liveMonitor.sh, which sources the location of the config file from ukmon.ini, and then passes this to the python script. 
```
source $here/ukmon.ini
python $here/liveMonitor.py $LOCATION $RMSCFG 
```
Meanwhile. the line in the python script that contains the hardcoded path is only invoked if the config file is not supplied as expected:
```
    if len(sys.argv) < 3:
        rmscfg = '/home/pi/source/RMS/.config'
    else:
        rmscfg = sys.argv[2]
```
This situation can only arise if the ukmon ini file is fatally damaged, or the script is invoked incorrectly. As the livestream needs the config file to determine where to find the logs, what the station ID is and so on, if the config file is not supplied, then nothing is going to work anyway.  In principle i could replace it by 
```
rmscfg = os.expanduser('~/RMS/.config')
```
and will do so, but this would still be wrong on a linux multistation build, and could be wrong on other code layouts.  There's no good answer :) 

Probably I should just abort if the config is not supplied, but i felt that since the vast majority of ukmon stations are running on 32-bit Pis so i could at least support their default setup. I have zero 64-bit builds to support at this stage, and in any events the current code will work on that platform.
